import Navbar from "@/components/Navbar";
import "./globals.css";
import { ReduxProvider } from "@/store/Provider";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Recipes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <ReduxProvider>{children}</ReduxProvider>
        <Footer />
      </body>
    </html>
  );
}
